// 세그먼트 길이 (초)
export const TITLE_DURATION_SECONDS = 3;
export const CONCEPT_DURATION_SECONDS = 5;
export const CODE_OVERVIEW_DURATION_SECONDS = 4;

// 라인별 설명 (각 4초)
export const LINE1_DURATION_SECONDS = 4;
export const LINE2_DURATION_SECONDS = 4;
export const LINE3TO5_DURATION_SECONDS = 5;
export const USAGE_DURATION_SECONDS = 4;

export const DIAGRAM_DURATION_SECONDS = 5;
export const SUMMARY_DURATION_SECONDS = 4;

// 전체 길이 계산
export const TOTAL_DURATION_SECONDS =
  TITLE_DURATION_SECONDS +
  CONCEPT_DURATION_SECONDS +
  CODE_OVERVIEW_DURATION_SECONDS +
  LINE1_DURATION_SECONDS +
  LINE2_DURATION_SECONDS +
  LINE3TO5_DURATION_SECONDS +
  USAGE_DURATION_SECONDS +
  DIAGRAM_DURATION_SECONDS +
  SUMMARY_DURATION_SECONDS;
