// 세그먼트 길이 (초)
export const HOOK_DURATION_SECONDS = 10;
export const PROBLEMS_DURATION_SECONDS = 20;
export const WHY_USE_DURATION_SECONDS = 15;
export const SOLUTION_DIFFICULTY_SECONDS = 15;
export const SOLUTION_SECURITY_SECONDS = 15;
export const SOLUTION_HALLUCINATION_SECONDS = 25;
export const SUMMARY_DURATION_SECONDS = 10;

// 전체 길이 계산
export const TOTAL_DURATION_SECONDS =
  HOOK_DURATION_SECONDS +
  PROBLEMS_DURATION_SECONDS +
  WHY_USE_DURATION_SECONDS +
  SOLUTION_DIFFICULTY_SECONDS +
  SOLUTION_SECURITY_SECONDS +
  SOLUTION_HALLUCINATION_SECONDS +
  SUMMARY_DURATION_SECONDS;
